# create file *.ts
touch PersonalCv.entity.ts
touch PersonalCvTranslate.entity.ts
touch PersonalCvTranslate.entity.ts
touch Language.entity.ts
touch Contact.entity.ts
touch ContactType.entity.ts
touch ContactTypeTranslate.entity.ts
touch Summary.entity.ts
touch User.entity.ts
touch CvTemplate.entity.ts
touch TemplateThemes.entity.ts
touch TemplateDownloadHistory.entity.ts
touch SummaryTranslate.entity.ts
touch SkillSet.entity.ts
touch SkillsTranslate.entity.ts
touch Skills.entity.ts
touch SkillSetTranslate.entity.ts
touch WorkExperiences.entity.ts
touch WorkExperienceTranslate.entity.ts
touch Projects.entity.ts
touch ProjectTranslate.entity.ts
touch ProjectDescription.entity.ts
touch ProjectDescriptionTranslate.entity.ts
touch Achievements.entity.ts
touch AchievementTranslate.entity.ts
touch LanguageSkills.entity.ts
touch LanguageSkillTranslate.entity.ts
touch EducationsExperiences.entity.ts
touch EducationsExperiencesTranslate.entity.ts
touch ParagraphBgImg.entity.ts