/* tslint:disable */
/* eslint-disable */
/**
 * my-cv-project-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthCheckResponse
 */
export interface HealthCheckResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof HealthCheckResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof HealthCheckResponse
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof HealthCheckResponse
     */
    timestamp: string;
}

/**
 * Check if a given object implements the HealthCheckResponse interface.
 */
export function instanceOfHealthCheckResponse(value: object): value is HealthCheckResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function HealthCheckResponseFromJSON(json: any): HealthCheckResponse {
    return HealthCheckResponseFromJSONTyped(json, false);
}

export function HealthCheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'status': json['status'],
        'message': json['message'],
        'timestamp': json['timestamp'],
    };
}

export function HealthCheckResponseToJSON(json: any): HealthCheckResponse {
    return HealthCheckResponseToJSONTyped(json, false);
}

export function HealthCheckResponseToJSONTyped(value?: HealthCheckResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'status': value['status'],
        'message': value['message'],
        'timestamp': value['timestamp'],
    };
}

