// src/server.ts
import app from "./app";
import { AppDataSource } from "./data-source";
import { RegisterRoutes } from "./routes/routes";

const port = process.env.PORT || 8080;

const initializeApiServer = async (): Promise<boolean> => {
    let databaseConnectedStatus = false;
    let routesRegisteredStatus = false;

    console.log("✅ [API Server] Initializing...\n");
    // connect to the database
    try {
        await AppDataSource.initialize().then(() => {
            databaseConnectedStatus = true;
            console.log("✅ [Database Connection] initialized successfully!");
        }).catch((error) => {
            console.error("❌ [Error] initializing database connection:", error);
        });
    } catch (error) {
        console.error("❌ [Error] initializing database connection:", error);
    }

    // use routes that were generated by tsoa
    try {
        RegisterRoutes(app);
        routesRegisteredStatus = true;
        console.log("✅ [TSOA Routes] registered successfully!");
    } catch (error) {
        console.error("❌ [Error] registering TSOA routes:", error);
    }

    return databaseConnectedStatus && routesRegisteredStatus;
};

initializeApiServer().then((isOnline: boolean) => {
    app.listen(port, () => {
        if (isOnline) {
            console.log("\n✅ [Server] started successfully");
            console.log(`✅ [Server] running on http://localhost:${port}/api`);
            console.log(`✅ [Swagger UI] http://localhost:${port}/api-docs`);
        } else {
            console.warn("❌ [Server] failed to start");
        }
    });
});